language: ruby
rvm:
  - 2.2.0
env:
  - DB=postgresql
script:
  - bundle exec rake test
before_script:
  - cp config/database.yml.sample config/database.yml
  - cp config/credentials.yml.sample config/credentials.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - mkdir tmp && mkdir tmp/cache
services:
  - redis-server
